#cloud-config

# Configure a limited user
users:
  - default
  - name: jasnlink
    groups:
      - sudo
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOUe4+8Y6qWQldnWi8ticdjDa7Mjho6CLMHpLnoRoI7O jasnlink"

# Perform System Updates
package_update: true
package_upgrade: true

# Harden SSH access
runcmd:
  - sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config
  - echo "PermitRootLogin no" >> /etc/ssh/sshd_config
  - systemctl restart sshd

# Install additional software packages
packages:
  - apache2
  - fail2ban
  - mariadb-server
  - ufw
  - redis
  - curl
  - libapache2-mod-wsgi

### Missing steps:
# curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash - 
# sudo apt-get install -y nodejs
# npm install pm2 -g
# install certbot
# Configure Apache VHOST
# Configure MYSQL DB and USER
# Add a second deploy user